<!DOCTYPE html>
<!-- Created By CodingNepal - www.codingnepalweb.com -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto Gasolinas </title>
    <link rel="stylesheet" href="Style/estiloshome.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
</head>
<body>
    
    <nav>
        <div class="wrapper">
        <div class="logo"><a href="#">Gasolinas</a></div>
        <ul class="nav-links">
        <label for="close-btn" class="btn close-btn"><i class="fas fa-times"></i></label>
        <li><a href="#">Home</a></li>
        <li><a href="ControlVentas.php">Control de ventas </a></li>
        <li><a href="VentasDia.php">Ventas Por Dia</a></li>
        <li><a href="VentasTotales.php">Ventas Totales</a></li>
        <li><a href="PrecioTotal.php">Total A Pagar  </a></li>
        </ul>
        <label for="menu-btn" class="btn menu-btn"><i class="fas fa-bars"></i></label>
        </div>
    </nav>

 
</body>
</html>